ecs_cluster=rest-service-dev-cluster
ecs_service=rest-service-dev-service
ecs_task_definition=rest-service-dev-task
container_name=rest-service
aws_region=us-east-1
ecr_repository=rest-service
iam_role=arn:aws:iam::289491622160:role/rest-service-dev-github-actions-ecs-deploy
cpu=512
memory=1024
