ecs_cluster=rest-service-uat-cluster
ecs_service=rest-service-uat-service
ecs_task_definition=rest-service-uat-task
container_name=rest-service
aws_region=us-east-1
ecr_repository=rest-service
iam_role=arn:aws:iam::289491622160:role/rest-service-uat-github-actions-ecs-deploy
cpu=1024
memory=2048
