ecs_cluster=frontend-app-sit-cluster
ecs_service=frontend-app-sit-service
ecs_task_definition=frontend-app-sit-task
container_name=frontend-app
aws_region=us-east-1
ecr_repository=frontend-app
iam_role=arn:aws:iam::289491622160:role/frontend-app-sit-github-actions-ecs-deploy
cpu=256
memory=512
