ecs_cluster=frontend-app-uat-cluster
ecs_service=frontend-app-uat-service
ecs_task_definition=frontend-app-uat-task
container_name=frontend-app
aws_region=us-east-1
ecr_repository=frontend-app
iam_role=arn:aws:iam::289491622160:role/frontend-app-uat-github-actions-ecs-deploy
cpu=512
memory=1024
